<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <UserSecretsId>gameplatform-tests-player-api</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions" Version="9.5.0" />
        <PackageReference Include="coverlet.collector" Version="6.0.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="Xunit.DependencyInjection" Version="9.9.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GamePlatform.Tests.Configuration\GamePlatform.Tests.Configuration.csproj" />
        <ProjectReference Include="..\GamePlatform.Tests.Infrastructure\GamePlatform.Tests.Infrastructure.csproj" />
        <ProjectReference Include="..\GamePlatform.Tests.Steps\GamePlatform.Tests.Steps.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\Config\appsettings.dev.json" Link="appsettings.dev.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\Config\appsettings.int.json" Link="appsettings.int.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\Config\appsettings.stage.json" Link="appsettings.stage.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
