<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.7" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GamePlatform.Tests.Configuration\GamePlatform.Tests.Configuration.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="OpenApi\PlayerApi.json" />
    </ItemGroup>

</Project>
